apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pvc
  namespace: gua
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
